# fly.toml app configuration file generated for fbstream3 on 2024-11-12T20:58:00+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fbstream3'
primary_region = 'mad'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = "tcp"
  internal_port = 1935

  [[services.ports]]
    port = 1935
    handlers = ["proxy_proto"]

[[services]]
  protocol = "tcp"
  internal_port = 8000
  
  [[services.ports]]
    port = 8000
    handlers = ["http"]


[[vm]]
  memory = '4gb'
  cpu_kind = 'performance'
  cpus = 2
